# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-20 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choice_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField(default=1, unique=True)),
                ('grade', models.FloatField()),
                ('questionContent', models.TextField()),
                ('questionSection', models.CharField(max_length=128)),
                ('answer1', models.TextField()),
                ('answer2', models.TextField()),
                ('answer3', models.TextField()),
                ('answer4', models.TextField()),
                ('rightAnswer', models.CharField(max_length=10)),
                ('diff', models.IntegerField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u9009\u62e9\u9898',
                'verbose_name_plural': '\u9009\u62e9\u9898',
            },
        ),
        migrations.CreateModel(
            name='fillin_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fillinId', models.IntegerField(default=1, unique=True)),
                ('grade', models.FloatField()),
                ('fillinContent', models.TextField()),
                ('answer1', models.TextField()),
                ('answer2', models.TextField()),
                ('answer3', models.TextField()),
                ('is_order', models.IntegerField()),
                ('fillinSection', models.CharField(max_length=128)),
                ('diff', models.IntegerField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u586b\u7a7a\u9898',
                'verbose_name_plural': '\u586b\u7a7a\u9898',
            },
        ),
        migrations.CreateModel(
            name='question_strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_number', models.IntegerField(default=5)),
                ('fillin_number', models.IntegerField(default=5)),
                ('essay_number', models.IntegerField(default=5)),
                ('discuss_number', models.IntegerField(default=5)),
                ('teacher', models.CharField(max_length=128)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u51fa\u9898\u7b56\u7565',
                'verbose_name_plural': '\u51fa\u9898\u7b56\u7565',
            },
        ),
    ]
