# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-20 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='choice_questions',
        ),
        migrations.DeleteModel(
            name='fillin_questions',
        ),
        migrations.DeleteModel(
            name='question_strategy',
        ),
    ]
