# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-21 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_chaper_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='choice_ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuId', models.CharField(max_length=255, unique=True)),
                ('questionId', models.IntegerField()),
                ('answer', models.CharField(max_length=255)),
                ('chapter', models.IntegerField()),
                ('is_final', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u9009\u62e9\u9898\u7b54\u9898\u8868',
                'verbose_name_plural': '\u9009\u62e9\u9898\u7b54\u9898\u8868',
            },
        ),
        migrations.CreateModel(
            name='fillin_ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuId', models.CharField(max_length=255, unique=True)),
                ('fillinId', models.IntegerField()),
                ('ans1', models.CharField(max_length=255)),
                ('ans2', models.CharField(max_length=255)),
                ('ans3', models.CharField(max_length=255)),
                ('is_final', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u586b\u7a7a\u9898\u7b54\u9898\u8868',
                'verbose_name_plural': '\u586b\u7a7a\u9898\u7b54\u9898\u8868',
            },
        ),
        migrations.DeleteModel(
            name='chaper_test',
        ),
    ]
