# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-21 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20190321_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice_ans',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fillin_ans',
            name='correct',
            field=models.IntegerField(default=0),
        ),
    ]
