# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20190321_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice_ans',
            name='questionId',
            field=models.IntegerField(default=1),
        ),
    ]
