# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-21 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_auto_20190321_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillin_ans',
            name='chapter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='choice_ans',
            name='chapter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fillin_ans',
            name='fillinId',
            field=models.IntegerField(default=1),
        ),
    ]
