# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20190321_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice_ans',
            name='stuId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fillin_ans',
            name='stuId',
            field=models.CharField(max_length=255),
        ),
    ]
