# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-22 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_auto_20190321_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='choice_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField(default=1)),
                ('grade', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': '\u5f53\u524d\u9009\u62e9\u9898\u533a\u5206\u5ea6',
                'verbose_name_plural': '\u5f53\u524d\u9009\u62e9\u9898\u533a\u5206\u5ea6',
            },
        ),
        migrations.CreateModel(
            name='fillin_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fillinId', models.IntegerField(default=1)),
                ('grade', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': '\u5f53\u524d\u586b\u7a7a\u9898\u533a\u5206\u5ea6',
                'verbose_name_plural': '\u5f53\u524d\u586b\u7a7a\u9898\u533a\u5206\u5ea6',
            },
        ),
    ]
