# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-22 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_auto_20190322_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_grade',
            name='question_name',
            field=models.CharField(default='choice', max_length=255),
        ),
    ]
