# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-22 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0012_auto_20190322_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_strategy',
            name='is_final',
            field=models.IntegerField(default=0),
        ),
    ]
