# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-29 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice_ans',
            name='chapter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fillin_ans',
            name='chapter',
            field=models.IntegerField(default=0),
        ),
    ]
