# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-29 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0017_auto_20190329_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(default=1)),
                ('choice', models.IntegerField(default=0)),
                ('fillin', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '\u9898\u76ee\u6570\u91cf',
                'verbose_name_plural': '\u9898\u76ee\u6570\u91cf',
            },
        ),
    ]
