# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-29 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0018_question_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_num',
            name='teacher',
            field=models.CharField(default='wang', max_length=128),
            preserve_default=False,
        ),
    ]
