# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-01 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0020_compose_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='compose_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('questionId', models.IntegerField(default=0)),
                ('teacher', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '\u9009\u62e9\u9898\u81ea\u7ec4\u5377',
                'verbose_name_plural': '\u9009\u62e9\u9898\u81ea\u7ec4\u5377',
            },
        ),
        migrations.CreateModel(
            name='compose_fillin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('fillinId', models.IntegerField(default=0)),
                ('teacher', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '\u586b\u7a7a\u9898\u81ea\u7ec4\u5377',
                'verbose_name_plural': '\u586b\u7a7a\u9898\u81ea\u7ec4\u5377',
            },
        ),
        migrations.DeleteModel(
            name='compose_test',
        ),
    ]
