# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-01 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0021_auto_20190401_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='compose_choice_ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuId', models.CharField(max_length=255)),
                ('questionId', models.IntegerField(default=1)),
                ('answer', models.CharField(max_length=255)),
                ('test_name', models.CharField(max_length=255)),
                ('correct', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u9009\u62e9\u9898\u7b54\u9898\u8868',
                'verbose_name_plural': '\u4efb\u52a1\u9009\u62e9\u9898\u7b54\u9898\u8868',
            },
        ),
        migrations.CreateModel(
            name='compose_fillin_ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuId', models.CharField(max_length=255)),
                ('fillinId', models.IntegerField(default=1)),
                ('ans1', models.CharField(max_length=255)),
                ('ans2', models.CharField(max_length=255)),
                ('ans3', models.CharField(max_length=255)),
                ('test_name', models.CharField(max_length=255)),
                ('correct', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u586b\u7a7a\u9898\u7b54\u9898\u8868',
                'verbose_name_plural': '\u4efb\u52a1\u586b\u7a7a\u9898\u7b54\u9898\u8868',
            },
        ),
    ]
