# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-01 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0022_compose_choice_ans_compose_fillin_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='compose_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_Id', models.CharField(max_length=255, unique=True)),
                ('test_name', models.CharField(max_length=255)),
                ('choice', models.IntegerField(default=0)),
                ('fillin', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '\u7ec4\u5377\u6210\u7ee9\u8868',
                'verbose_name_plural': '\u7ec4\u5377\u6210\u7ee9\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': '\u666e\u901a\u6210\u7ee9\u8868', 'verbose_name_plural': '\u666e\u901a\u6210\u7ee9\u8868'},
        ),
    ]
