# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-09 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0024_compose_score_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice_questions',
            name='diff',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='choice_questions',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fillin_questions',
            name='diff',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fillin_questions',
            name='grade',
            field=models.FloatField(default=0),
        ),
    ]
