# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-09 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0025_auto_20190409_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice_questions',
            name='questionId',
            field=models.IntegerField(unique=True),
        ),
    ]
