# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-20 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
