# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-24 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=datetime.datetime(2019, 3, 24, 14, 5, 30, 587000, tzinfo=utc), upload_to='images/%Y/%m', verbose_name='\u6587\u4ef6\u7f29\u7565\u56fe'),
            preserve_default=False,
        ),
    ]
