# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-25 07:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_delete_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(default=datetime.datetime(2019, 3, 25, 7, 2, 14, 576000, tzinfo=utc), upload_to='student_Pic/'),
            preserve_default=False,
        ),
    ]
