# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-27 04:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_major_stu_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_class',
            name='major_id',
        ),
        migrations.AddField(
            model_name='stu_class',
            name='major',
            field=models.CharField(default=datetime.datetime(2019, 3, 27, 4, 45, 45, 468000, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
    ]
