# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-27 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20190327_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='major',
        ),
    ]
