# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-10 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20190327_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$24000$vkmI2oWEdlFs$NCo6Ju6kbXM9ZStyrd0m/mGjIdyyUD4zXH2CykFxe3Q=', max_length=256),
        ),
    ]
