# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-10 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20190410_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$24000$4HaFHdKYzI9f$ke1kmm0OKHgpJparlyOHynIBaXg0i2PxARd3btshHU0=', max_length=256),
        ),
    ]
