# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-16 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20190416_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='support',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='support',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$24000$qXKGWDCdZLbh$/rwLTHssko6lSj5yqlGmUMTTO9NL/mDf6XERRR9kk64=', max_length=256),
        ),
    ]
