# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-16 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20190416_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_teacher',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='is_teacher',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$24000$esa0AABMlXO8$vWARx8eu0adJH1U1m21C8ExPRBlcHlPERoKjrR3xDqo=', max_length=256),
        ),
    ]
