# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-16 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_auto_20190416_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pic',
            field=models.CharField(default=datetime.datetime(2019, 4, 16, 8, 14, 13, 857000, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$24000$hYFvQQOO3431$z0m4zdgcmA8LcO58pMbKQIB+75A2vSbPv2w4T+qbJJE=', max_length=256),
        ),
    ]
