# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-25 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_auto_20190425_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$24000$VKRS3vBZLpHI$rtlUUtaXHt3VWA8/eGOo9uZIG/R1MYwODuDuoZoeH7o=', max_length=256),
        ),
    ]
